### ISSUE TITLE
SOAP Error: There is no user account for this user name.

### ISSUE THREAD

**Issue by mmdollar** [ole1986/wp-ispconfig3#1]
Is there any documentation about how to setup the templates? I added the remote user and after I tried registering a new user this error shows up:
SOAP Error: There is no user account for this user name.

I am using ISPConfig 3.1 and wordpress 4.6.1 .

I just installed the plugin made a new post and inserted [ispconfig class=IspconfigRegisterFree] the form appeared nicely but sadly cannot register a user. Does my template in ISPConfig need to match the same ID number and name as the ones in the .php file?

**Comment by ole1986** [comment]
@mmdollar  welcome,
unfortunately there is no detailed documentation which covers your issue.

First it is required that the user is listed as "remote user" in the ispconfig "system settings" (see screenshot):

![image](https://cloud.githubusercontent.com/assets/4850116/19534720/3a8221fe-9645-11e6-8312-e4ee7fa58d8b.png)

The template ID defined in the property `$FreeTemplateID` when using  the IspconfigRegisterFree (ispconfig_register_free.php) must of course match the ID which is stored in the ispconfig database (table: client_template).

I recommend you to test with [ispconfig class=IspconfigRegisterClient]. It does not require any additional templates (etc...) - Only a proper remote user with password is neccessary of course.

For further questions, dont hesitate to ask :-)

**Comment by ole1986** [comment]
@mmdollar I just noticed there are some changes made in to ISPConfig REST API.

I am going to update the plugin on github first... and within the next day it will be available on wordpress as well.

**Comment by mmdollar** [comment]
Thanks a lot, awesome plugin you got there ! :) I will wait for the update.
