### ISSUE TITLE
Plugin Woocommerce

### ISSUE THREAD

**Issue by MisTerM7** [ole1986/wp-ispconfig3#11]
Hello
The plugin Woocommerce when installed, faut'il a particular configuration?
Mz

**Comment by ole1986** [comment]
do you have any errors to report

**Comment by ole1986** [comment]
mhm.... no answer?!

**Comment by MisTerM7** [comment]
Hello
I managed to install it and set it up with Woocommerce.
But then I drop the plugin in the sense that I realized that there was another plugin to do this kind of action.
Mz
