### ISSUE TITLE
Filter wordpress users in Websites/Databases other than "customer" role

### ISSUE THREAD

**Issue by ole1986** [ole1986/wp-ispconfig3#17]
It was requested to select users which are not only WooCommerce "customers".

Therefore it may be a good option to extend the "Settings" page allowing the user to defined which role a user should be selected from.

![image](https://user-images.githubusercontent.com/4850116/53018338-64865a80-3452-11e9-963b-84e5e39562d8.png)

**Comment by MachineITSvcs** [comment]
Maybe even provide a check boxes selection to choose multiple User Roles. Then just check to see if the same key exists in both the selected (checked) roles and user’s roles.
