### ISSUE TITLE
Open Registration

### ISSUE THREAD

**Issue by mmdollar** [ole1986/wp-ispconfig3#2]
When I use [ispconfig class=IspconfigRegisterFree] for my registration form (I have created a Free User Template from ISPConfig) the plugin uses it creates a user but it gives some errors:
`SOAP Error: directory_error_notinweb
#0 /var/www/clients/client5/web3/web/wp-content/plugins/wp-ispconfig3/ispconfig_register.php(269): SoapClient->__call('sites_shell_use...', Array) #1 /var/www/clients/client5/web3/web/wp-content/plugins/wp-ispconfig3/ispconfig_register.php(269): SoapClient->sites_shell_user_add('727a16e38db6d71...', '13', Array) #2 /var/www/clients/client5/web3/web/wp-content/plugins/wp-ispconfig3/ispconfig_register_free.php(95): IspconfigRegister->AddShell(Array) #3 /var/www/clients/client5/web3/web/wp-content/plugins/wp-ispconfig3/ispconfig_register_free.php(136): IspconfigRegisterFree->onPost() #4 /var/www/clients/client5/web3/web/wp-content/plugins/wp-ispconfig3/ispconfig_register.php(92): IspconfigRegisterFree->Display(Array) #5 [internal function]: IspconfigRegister->shortcode(Array, '', 'ispconfig') #6 /var/www/clients/client5/web3/web/wp-includes/shortcodes.php(326): call_user_func(Array, Array, '', 'ispconfig') #7 [internal function]: do_shortcode_tag(Array) #8 /var/www/clients/client5/web3/web/wp-includes/shortcodes.php(223): preg_replace_callback('/\\[(\\[?)(ispcon...', 'do_shortcode_ta...', 'No CLASS parameter defined in shortcode: do_shortcode('[ispconfig clas...') #10 /var/www/clients/client5/web3/web/wp-includes/plugin.php(235): call_user_func_array('do_shortcode', Array) #11 /var/www/clients/client5/web3/web/wp-includes/post-template.php(240): apply_filters('the_content', '[ispconfig clas...') #12 /var/www/clients/client5/web3/web/wp-content/themes/blue/content.php(110): the_content('Read More »...') #13 /var/www/clients/client5/web3/web/wp-includes/template.php(574): require('/var/www/client...') #14 /var/www/clients/client5/web3/web/wp-includes/template.php(531): load_template('/var/www/client...', false) #15 /var/www/clients/client5/web3/web/wp-includes/general-template.php(167): locate_template(Array, true, false) #16 /var/www/clients/client5/web3/web/wp-content/themes/blue/page.php(13): get_template_part('content', 'page') #17 /var/www/clients/client5/web3/web/wp-includes/template-loader.php(75): include('/var/www/client...') #18 /var/www/clients/client5/web3/web/wp-blog-header.php(19): require_once('/var/www/client...') #19 /var/www/clients/client5/web3/web/index.php(17): require('/var/www/client...') #20 {main}`

And it does not create a new subdomain for the website, but everything else works fine. Maybe I am doing something wrong? I am using the default template for the DNS.

**Comment by ole1986** [comment]
Hi, 

is the shell user being created?
Also, what version of ISPConfig are you using?

the free script should create:
- client (username)
- website (subdomain part . DOMAIN OPTION)
- shell (username_shell)

**Comment by mmdollar** [comment]
It does not create a shell user. I am using the latest version of ISPConfig 3.1.1p1 Multiserver setup. Ok I just saw that on my Free Hosting template, Shell user = 0 maybe that is the problem? Should the script also add a Customer Number, cause atm that is missing? Overall great job :)

**Comment by ole1986** [comment]
@mmdollar yes this might be the problem - you can also remove the line where its creating the shell account or create your own _ispconfig_register_free2.php_ for instance

I am pretty sure there will come more (currently focusing on woocommerce related things)

Let me know if your issue is fixed, so I can close it here.
Thank you

**Comment by mmdollar** [comment]
Ok so I tried to add a shell user = 1 in ISPConfig template but the error is still the same. So I commented out the shell user part in the php script and now everything works fine, no errors email is sent to the user and the username is added to ISPConfig. Sadly it does not add the domain on my nameservers, probably an error on my part I will look into it. You can close the issue.
