### ISSUE TITLE
Make use of Gutenberg blocks

### ISSUE THREAD

**Issue by ole1986** [ole1986/wp-ispconfig3#20]
While I have already started in branch [wp-blocks](https://github.com/ole1986/wp-ispconfig3/tree/wp-blocks) to include gutenberg blocks I am actually struggling with the concept on how to deal with all the possible fields available in ISPConfig3

Would be good to have you involved @MachineITSvcs.
So, that I know in which situation you have used your implemented method `Ispconfig->UpdClient([...])`

**Comment by MachineITSvcs** [comment]
The UpdClient function is used in the example cancelled method, and can also be used for switching master templates, updating passwords, limits, etc. Maybe utilize it on a form (for logged in users) that either creates or updates the ISPConfig user account by the same name as the WordPress username, depending on whether or not the user already exists. I would recommend providing this function only when a username is gathered automatically to avoid an existing user from being updated by someone else. I assume you’re turning this into some kind of form builder? I’m unable to look at the code presently, but if that is correct, then I recommend only utilizing that function when the username field does not exist in the form. I will look at the branch later today.

**Comment by ole1986** [comment]
To update (or manage) ISPconfig users based on their wordpress login I was more thinking of a small plugin, the developer can create for each action individually

Currently wp-blocks branch supports the following actions (but this may change):

* ispconfig_block_action_create_client
* ispconfig_block_action_create_website
* ispconfig_block_action_create_website_new
* ispconfig_block_action_update_client

Below would be a working example plugin

```
<?php
/*
Plugin Name: Ispconfig client2user
Plugin URI: http://URI_Of_Page_Describing_Plugin_and_Updates
Description: Always overwrite the ISPConfig client id to its logged in wp_user.
Version: 1.0
Author: ole1986
License: GPL2
*/

add_filter('ispconfig_block_action_update_client', function($fields) {

    $user = wp_get_current_user();

    array_walk($fields, function(&$item) use($user) {
        if($item['id'] == 'client_username') $item['value'] = $user->user_login;
    });

    return $fields;
});
```

This will overwrite the "action" known as "Update client" (may change in future) to always use the logged in account.

There will be other actions available of course (E.g. "Update bank details") which can easily be included through the `add_filter` callback.

And even more, it could overwrite the default values (being set by the gutenberg block) from different sources.

**Comment by ole1986** [comment]
@MachineITSvcs I have updated the wp-blocks branch so, that I could actually get rid of the shortcodes (including the "canceled" one).

It would be really helpful you can test it and let me know what you think about it.
Please note that this is still not release and errors/problems may occur.

Thank you in advanced

**Comment by MachineITSvcs** [comment]
After re-reading your previous message, I noticed you said you may change the Client Update function in the future to always use the logged in user. How I currently use this function is to detect on web hosting (subscription checkout) if the client already exists and update it if necessary. This also runs on every recurring payment, and the canceled method is used when a payment is failed or subscription canceled. So using the logged in user would not be a good idea, as the username needs to be able to get passed into the function on a backend recurring payment for example.

**Comment by ole1986** [comment]
Well, the action/filter hook can actually be used to overwrite the username and other fields dependent on the action being used.

The only difficulty I see now from your last comment, is that you are using such Shortcodes to immediately call an ISPconfig soap action instead of waiting for a user input. Is this correct?!

Can you explain how you trigger the shortcode in recurring payments

**Comment by MachineITSvcs** [comment]
That is correct. This is how I’ve always done it, but I also have another custom method besides canceled for this purpose. Would you like me to include both here as examples? They are fairly basic.

**Comment by MachineITSvcs** [comment]
I created a must-use plugin for the initial subscription/recurring payments. Here is an example:

`add_action( 'woocommerce_payment_complete', 'hosting_package_checkout' );
function hosting_package_checkout( $order_id ){
        //This is where you can set a product/variation id to variables for template assignment
        $product_parent_id = 1234;
        $product_variation_template_example_1 = 2341;
        $product_variation_template_example_2 = 3412;
        $product_variation_template_example_3 = 4123;
        //This is so you can check if one of these products is in an order after payment has completed
        $order = wc_get_order($order_id);
        $order_data = $order->get_data();
        $user_id = $order->get_user_id();
        foreach ( $order->get_items() as $item ) {
                if ( $item['product_id'] > 0 ) {
                        $_product = $order->get_product_from_item( $item );
                        if ( $_product->parent_id == $hosting_package_parent ) {
                                session_start();
                                include ('wp-includes/pluggable.php');
                                $isp_contact = $order_data['billing']['first_name'] . " " . $order_data['billing']['last_name'];
                                $isp_company = $order_data['billing']['company'];
                                $isp_email = $order_data['billing']['email'];
                                //Gathers user information from order including username and id, and generates a password using wp_generate_password function
                                $user_info = get_userdata($user_id);
                                $isp_username = $user_info->user_login;
                                $isp_customerno = $user_info->ID;
                                $isp_password = wp_generate_password();
                                if ( $item->get_variation_id() == $product_variation_template_example_1 ) {
                                        $isp_template = 1;
                                } elseif ( $item->get_variation_id() == $product_variation_template_example_2 ) {
                                        $isp_template = 2;
                                } elseif ( $item->get_variation_id() == $product_variation_template_example_3 ) {
                                        $isp_template = 3;
                                }
                                echo hosting_package_account_creation($isp_contact, $isp_company, $isp_email, $isp_username, $isp_customerno, $isp_password, $isp_template);
                        }
                }
        }
}

function hosting_package_account_creation($isp_contact, $isp_company = '', $isp_email, $isp_username, $isp_customerno = '', $isp_password, $isp_template) {
        if($isp_contact != '' && $isp_email != '' && $isp_username != '' && $isp_password != '' && $isp_template != '') {
                return do_shortcode('[ispconfig class=IspconfigRegisterHosting contact="' . $isp_contact . '" company="' . $isp_company . '" email="' . $isp_email . '" username="' . strtolower($isp_username) . '" customerno="C' . $isp_customerno . '" password="' . $isp_password . '" template="' . $isp_template . '"]');
        }
}`

As you can see, I used a custom Hosting method. The code for this is as follows:

`class IspconfigRegisterHosting extends Ispconfig {
        public function Display($attr){
                $this->onPost($attr);
        }
        private function onPost($attr){
        try{
            if(!empty($attr['email']) && !empty($attr['username'])) {
                $client = $this->withSoap()->GetClientByUser(strtolower($attr['username']));
                $opt = ['company_name' => ($attr['company'] ? $attr['company'] : '' ),
                        'contact_name' => $attr['contact'],
                        'state' => (isset($attr['state']) ? $attr['state'] : ''),
                        'country' => (isset($attr['country']) && $attr['country'] != '') ? $attr['country'] : 'US'),
                        'email' => $attr['email'],
                        'username' => strtolower($attr['username']),
                        'customer_no' => ($attr['customerno'] ? $attr['customerno'] : ''),
                        'template_master' => $attr['template'],
                        'locked' => 'n',
                        'canceled' => 'n'
                ];
                if(empty($client)) {
                        $passwdopt = [ 'password' => $attr['password'] ];
                        $opt = array_merge($opt, $passwdopt);
                        $this->AddClient($opt);
                        if(!empty(WPISPConfig3::$OPTIONS['confirm'])) {
                                $sent = $this->SendConfirmation($opt);
                        }
                } else {
                        $client_id = $client['client_id'];
                        $this->UpdClient($opt, $client_id);
                }
            }
            $this->closeSoap();
        } catch (SoapFault $e) {
            echo '<div class="ispconfig-msg ispconfig-msg-error">SOAP Error: '.$e->getMessage() .'</div>';
        } catch (Exception $e) {
            echo '<div class="ispconfig-msg ispconfig-msg-error">Exception: '.$e->getMessage() . "</div>";
        }
    }
}`

Maybe this will give you an idea of how to integrate WooCommerce Subscriptions into the plugin natively, similar to how you already have the Webspace option (which I don't use) or with a premium add-on ;) (If you do, I hope we could partner on that as well). Let me know if you have any other questions!

**Comment by MachineITSvcs** [comment]
I would prefer to email you the code actually

**Comment by MachineITSvcs** [comment]
They have been sent.

**Comment by ole1986** [comment]
I have improved the use of custom shortcode classes, allowing you to put the files outside of the wp-ispconfig3 plugin.

Check out [this wiki page](https://github.com/ole1986/wp-ispconfig3/wiki/Extending-wp-ispconfig3-with-custom-shortcodes) on how to upgrade and implement for version 1.4.0

**Comment by ole1986** [comment]
@MachineITSvcs I am planning to release this version soon. Does the changes fit to your needs?
