### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by csib** [ole1986/wp-ispconfig3#22]
![kép](https://user-images.githubusercontent.com/24816101/65815130-6b94f880-e1eb-11e9-816a-e8cc9ae7d9f6.png)

The translations are not working properly with the latest WP (5.2.3) Your plugin is awesome, thanks for sharing the project. Do you plan to continue developing it?

Regards,
csib

**Comment by ole1986** [comment]
Hi @csib 

can you tell me what language you have chooses in your wordpress installation?

Whenever I have time of course I am going to work on this project.
If you think there is a feature missing, feel free to post a new issue and describe your feature request.

**Comment by csib** [comment]
I have choosed Hungarian. Loco translate not recognized the translation automatically, by the way if I create manually wp-ispconfig3-hu_HU.mo +po and wp-ispconfig3-block-hu_HU.po +mo it seems working.

**Comment by ole1986** [comment]
Thank you for reporting.
I haven't had the chance to translate to other languages than english and german.

But I will try to add english as fallback language soon

**Comment by ole1986** [comment]
Unfortunatelly there is no fallback option available. So I recommend to switch your wordpress page to english which is always fully supported.

Alternatively you can take part of the translation
Check out the files:
https://github.com/ole1986/wp-ispconfig3/blob/master/lang/wp-ispconfig3-block-en_US.po
https://github.com/ole1986/wp-ispconfig3/blob/master/lang/wp-ispconfig3-de_DE.po

and translate them into your preferred language. Then either do a pull request or attach the po files here

Thank you
