### ISSUE TITLE
FR - Support the whole workflow for website creating

### ISSUE THREAD

**Issue by csib** [ole1986/wp-ispconfig3#23]
Feature Request

Support the whole workflow for website creating, which means, register the client, register a site, then register a database, and FTP account for the user, and register default e-mail addresses too.
postmaster@host.ltd
info@host.ltd

After everything is set-up send an e-mail to the customer with the credentials.

**Comment by ole1986** [comment]
There is not yet a workflow but a form which allows you to create the client and website at once.
Using the Gutenberg Blocks you need to select "Create Website (new client)" from the drop down.

This should display a form on the front page asking for company details and a website domain (while the website domain can also parse "GET data" information).

Once the "Customer" filled up the form and submit it A client is being created through the ISPConfig Rest API and a website with the given domain is added into it.

I know that this is not much atm. Unfortunately I did not have the time to improve the fields to put more flexibility into it.

**Comment by ole1986** [comment]
Related to #25

**Comment by ole1986** [comment]
This is partially implemented into 1.5.0 but still work to do
