### ISSUE TITLE
Integrate wizard options into WP-ISPConfig Blocks

### ISSUE THREAD

**Issue by ole1986** [ole1986/wp-ispconfig3#25]
Since WP-ISPConfig supports Gutenberg blocks I would want to have it more comfortable.
Something like a wizard implementation allowing to build up several pages and keep the previous information in session.

For example:

A client registration is filled up, and then redirected to the website creation "page" containing the previous client registration info in session. Once Website domain has been chosen it will redirect to FTP creation "page" or finalize the process while storing all into ISPConfig database.

**Comment by ole1986** [comment]
**Client**
Configure the client form to be a randomly generated user account and store wordpress and ISPConfig
*Continue with the next page for website input*

![client](https://user-images.githubusercontent.com/4850116/68531146-893b9e80-030f-11ea-922c-86d92cc99772.png)

**Website**
Configure the website form to fetch the client information from session
*Continue with the next page for database input*

![database](https://user-images.githubusercontent.com/4850116/68531147-89d43500-030f-11ea-88d6-58be2291dc19.png)

**Database**
*Save all data (incl. those which are still in session)*
Also configure the database form to fetch the client details from session
![website](https://user-images.githubusercontent.com/4850116/68531148-89d43500-030f-11ea-8c97-5630a43dc8f5.png)

**Comment by unuxm** [comment]
Where the link leads  /wp-ispconfig/wp-ispco.........?????

**Comment by ole1986** [comment]
It is supposed to be a new page containing another WP-Ispconfig Block.

I always would want to have this managed by blocks only but didn't had the chance to implement it...

Hopefully I will get this to work some day

**Comment by unuxm** [comment]
And how do I implement the creation of a client and site that is already an existing user, not during registration? Thank you in advance!

**Comment by ole1986** [comment]
Check out the screenshot from [here](https://github.com/ole1986/wp-ispconfig3/issues/25#issuecomment-552111526)

**Create Client**
In the first step a new client user is being generated using the "Create Client" WP-ISPConfig Block type and you can optionally include user information from a logged in wordpress user. 
Then you would setup the "Action" to `Continue with...` the next page (in your example another page containing a WP-ISPConfig block of type "Create Website")

**Create Website**
In this step a WP-ISPConfig Block of type "Create Website" is being used with the `Client ID` of `Session` to tell that it use the previously `generated` account (from the "Create Client" page).
Then you choose the `Save` action to save it into ISPConfig3
