### ISSUE TITLE
ISPConfig SOAP Request failed: Could not connect to host

### ISSUE THREAD

**Issue by WebWeave** [ole1986/wp-ispconfig3#3]
Hello,

First of all great work on making a plugin for this!
But when trying to add a product. 
I am getting this error: "ISPConfig SOAP Request failed: Could not connect to host"

They are on the same server, wordpress and ispconfig both use a letsencrypt ssl certificate.

Thanks in advance!

**Comment by ole1986** [comment]
Hi @WebWeave 

I can tell you I am also using letsencrypt...
And actually the message "Could not connect to host" sounds like it is not properly running on the host...

I am running it on port :8080
So, please make sure the below process is available using `netstat -anp |grep fcgi-pm`
```
tcp6       0      0 :::443                  :::*                    LISTEN      1237/fcgi-pm
tcp6       0      0 :::8080                 :::*                    LISTEN      1237/fcgi-pm <--
tcp6       0      0 :::80                   :::*                    LISTEN      1237/fcgi-pm
```

**UPDATE**

Also check the settings, so you have entered SOAP_URL and SOAP_LOCATION properly in Wordpress

```
SOAP Location: https://yourHost:8080/remote/index.php
SOAP Url: https://yourHost:8080/remote/
```

**Comment by WebWeave** [comment]
@ole1986 
When I run the command `netstat -anp |grep fcgi-pm` It doesnt show the process.
I however do can connect to the ispconfig control panel.
So this means that fastcgi is not working propperly right?

**Comment by ole1986** [comment]
https://www.howtoforge.com/community/threads/soap-error-could-not-connect-to-host.60623/
