### ISSUE TITLE
The given username already exists in the other system

### ISSUE THREAD

**Issue by milenmk** [ole1986/wp-ispconfig3#34]
With the last update v1.5.4, when "Create WordPress user" is not checked and the ClientID in the "client create" form is the same as an already registered user, I get the above-mentioned error "The given username already exists in the other system". If "client name" and "client e-mail" match an already registered user and Client ID is set to "generated, read-only" it's ok.

In addition to the above, when using "generated" for Client ID, the form shows one id like "054891fb73", but the user is created with another generated ID.  I presume, that clicking "Create client" generates another ID that is sent to ISPConfig.

**Comment by ole1986** [comment]
Your second statement is true. It's generation another random id once you submit.

Regarding your other issue just let me know from your perspective what should be your expected behavior and I can make it to work for you

**Comment by milenmk** [comment]
To my opinion, when WordPress user is not created, username and e-mail shouldn't be checked for matching an existing one in wp database.

**Comment by ole1986** [comment]
You are right... that makes sense but only when the newly added option "Create WordPress user" is unhooked of course
I will fix it asap
