### ISSUE TITLE
Capability issue

### ISSUE THREAD

**Issue by milenmk** [ole1986/wp-ispconfig3#35]
When DISALLOW_FILE_EDIT is set to true (for security reasons), the admin menu disappears due to the module capability "edit_themes" that is set.

On "index.php", lines 196, 200 and 202 change 'edit_themes' to 'manage_options' and all works fine.

**Comment by ole1986** [comment]
Feel free to provide a PR. So we can quickly merge things together

**Comment by milenmk** [comment]
Done

**Comment by ole1986** [comment]
Sorry... bit delayed... I will merge is asap
