### ISSUE TITLE
I'm Confused About This Plugins Usage

### ISSUE THREAD

**Issue by openthesource** [ole1986/wp-ispconfig3#6]
Is this plugin suppose to be accessible to the public?
Is it so people can buy hosting and have the accounts created?
 Is this a way of selling hosting using WordPress? Or is this only suppose to be for the admin?

**Comment by ole1986** [comment]
@openthesource 

It started with a plugin to allow a guest user to register webspace "templates" into the Ispconfig by using the REST API. 

When woocommerce ist installed products for webspace become available allowing the admin to assign Ispconfig client templates.

Also it includes a proper connection to the WC Order and can generate PDF invoices from the Order.

Finally some parts (not completed yet) to manage Ispconfig clients, domain's,  directly from WordPress will also take place in this plugin. For example Disable a domain, when customer did not pay the invoice, etc...

**Comment by openthesource** [comment]
Amazing. Do you plan to integrate it will the ISPconfig plugins?

What languages would one need to understand developing ISPconfig?

Sent from my HTC Phone.

----- Reply message -----

**Comment by ole1986** [comment]
@openthesource Well the focus is to have all in wordpress so the wont be a need of having a plugin in ISPConfig.

If you are interested in developing things for the plugins I recommend you to learn PHP OOP.
Same applies to the ISPconfig web panel.

**Comment by openthesource** [comment]
Very nice

Sent from my HTC Phone.

----- Reply message -----
