### ISSUE TITLE
cannot connect in the backend

### ISSUE THREAD

**Issue by ghost** [ole1986/wp-ispconfig3#7]
why am I getting  ISPConfig SOAP Request failed: Could not connect to host

does it have to do with ssl certificate? my ssl certificate is self signed.

**Comment by ole1986** [comment]
Either this or the host is not reachable.
If its the self signed certificate zou can workaround it the following:
https://stackoverflow.com/questions/8443618/disable-certificate-verification-in-php-soapclient

**Comment by ghost** [comment]
if I type the address in the browser it works ( https://198.58.105.50:8080/remote/index.php )

I get the blank screen and no errors in the console.

**Comment by ole1986** [comment]
Please try the recommended workaround it seem to be a problem with your self signed certificate

**Comment by ghost** [comment]
if you check now I changed the certificate to a valid one

this is how I installed soap, apt-get install php7.0-soap

also does it matter if i use my hostname or ip address

**Comment by ole1986** [comment]
I assume that the certificate is signed to a domain..
So it matters to use the domain name instead

**Comment by ghost** [comment]
yes I am using the domain name instead  https://revelhost.net

it works in the browser but not in the wocommerce product data webspace

**Comment by ghost** [comment]
my hostname cant be reached in the brouser, is that a problem?

```
This site can’t be reached

server1.revelhost.net took too long to respond.
```

**Comment by ole1986** [comment]
the host server1.revelhost.net does not seem to be a valid subdomain as it is unknown the the NS server

The nameserer should at least return an ip to be reachable
`dig @ns1.revelhost.net server1.revelhost.net` does not return any ip

I am closing this issues as this seem to be a configuration thing and has nothing to do with wp-ispconfig3

**Comment by broros** [comment]
one more thing, port 8080 is returning  Error while fetching URL.  at  https://httpstatus.io/
could this be why?   the port is open and working
