### ISSUE TITLE
The domain is already registered

### ISSUE THREAD

**Issue by ghost** [ole1986/wp-ispconfig3#9]
it keeps saying "The domain is already registered" for every domain I put in even if the domain is not registered in my account

![untitled](https://user-images.githubusercontent.com/598228/28547082-1811f852-7082-11e7-8234-beacd94d9d1a.jpg)

**Comment by ole1986** [comment]
It uses the command 'whois' on a Linux system you can double check domain by using `whois domain.tld`

**Comment by ghost** [comment]
it should only check domain names registered in ispconfig

**Comment by ole1986** [comment]
no it does not but I like your idea

**Comment by ghost** [comment]
so how the hell can I registered for a hosting service when the domain name has been purchased

**Comment by ole1986** [comment]
well usuall the whois allows you to check globally (lika all over the world) if someone has registere a domain.

for example: when you whois a domain which is free, like: ab44fggh.de

You get a result fron the whois: %ERROR:101: no entries found
This domain you can then register

But of course if you try to register a domain test.de which is already registered it wont work.

So the registration is supposed to check globally not only what is in your "domains list"

**Comment by RodriAndreotti** [comment]
I imagine that so-and-so means in cases where the client already has a contracted domain for some reason (he can have the site on another host and wants to migrate to ours, or he can only have the email service, anyway, he already has the domain) and wants to bring the hosting service to our server.

**Comment by Christian1998** [comment]
Hmm, it seems this plugin isnt ready for production enviroment...
(Yea 2018 and 2019)

**Comment by MachineITSvcs** [comment]
Why do you say that? I currently use it in production and it works without fail. Would you like to ask a question before falsely stating something as matter of fact?

**Comment by ole1986** [comment]
with issue #24 this should be resolved
